
# Lab 3 - Multiparticle Systems

## IMPORTANT WARNING: Variables names are re-used frequently, so make sure to execute all parts of a question in order.

In [2]:
from pylab import *

Functions to define spin-$s$ matrices:

In [3]:
def spinx(s):

    n = int(2.0*s+1)
    sx = matrix(zeros((n,n)))
    for a in range(0,n):
        for b in range(0,n):
            if (a==b+1):
                sx[a,b] = sx[a,b] + 0.5*sqrt((s+1)*(a+b+1)-(a+1)*(b+1))
            elif (a==b-1):
                sx[a,b] = sx[a,b] + 0.5*sqrt((s+1)*(a+b+1)-(a+1)*(b+1))
                
    return sx


def spiny(s):
    n = int(2.0*s+1)
    sy = matrix(zeros((n,n),dtype='complex'))

    for a in range(0,n):
        for b in range(0,n):
            if (a==b+1):
                sy[a,b] = sy[a,b] + 0.5j*sqrt((s+1)*(a+b+1)-(a+1)*(b+1))
            elif (a==b-1):
                sy[a,b] = sy[a,b] - 0.5j*sqrt((s+1)*(a+b+1)-(a+1)*(b+1))
                
    return sy
    
def spinz(s):
    
    n = int(2.0*s+1)
    sz = matrix(zeros((n,n)))

    for a in range(0,n):
        for b in range(0,n):
    
            if (a==b):
                sz[a,b] = (s+1-b-1)
                
    return sz

### Higher Spins

1. Generate $s=2$ matrices and calculate $\left[\hat{S}^{x},\hat{S}^{y}\right]$:

In [4]:
sx = spinx(2)
sy = spiny(2)
sz = spinz(2)

print(sx*sy-sy*sx)

[[0.+2.00000000e+00j 0.+0.00000000e+00j 0.+0.00000000e+00j
  0.+0.00000000e+00j 0.+0.00000000e+00j]
 [0.+0.00000000e+00j 0.+1.00000000e+00j 0.+0.00000000e+00j
  0.+0.00000000e+00j 0.+0.00000000e+00j]
 [0.+0.00000000e+00j 0.+0.00000000e+00j 0.-8.71111819e-17j
  0.+0.00000000e+00j 0.+0.00000000e+00j]
 [0.+0.00000000e+00j 0.+0.00000000e+00j 0.+0.00000000e+00j
  0.-1.00000000e+00j 0.+0.00000000e+00j]
 [0.+0.00000000e+00j 0.+0.00000000e+00j 0.+0.00000000e+00j
  0.+0.00000000e+00j 0.-2.00000000e+00j]]


Generally, for arbitrary $s$, one finds

$$\left[\hat{S}^{x},\hat{S}^{y}\right] = i\hbar\hat{S}^{z}$$

2. Calculate $\hat{S}^{2}$ for different values of $s$:

In [5]:
def Ssq(s):
    sx = spinx(s)
    sy = spiny(s)
    sz = spinz(s)
    
    s2 = sx**2 + sy**2 + sz**2
    
    return s2

In [6]:
print(Ssq(0.5))

[[0.75+0.j 0.  +0.j]
 [0.  +0.j 0.75+0.j]]


In [7]:
print(Ssq(1.0))

[[2.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 2.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 2.+0.j]]


In [8]:
print(Ssq(1.5))

[[3.75+0.j 0.  +0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 3.75+0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 3.75+0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.  +0.j 3.75+0.j]]


In [9]:
print(Ssq(2.0))

[[6.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 6.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 6.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 6.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 6.+0.j]]


General case: $\hat{S}^{2} = s(s+1)\hbar^{2}\hat{I}$.

3. Commutators of spin components with $\hat{S}^{2}$ for $s = \frac{3}{2}$:

In [10]:
s = 1.5
S2 = Ssq(s)
sx = spinx(s)
sy = spiny(s)
sz = spinz(s)

(a) $\left[\hat{S}^{2},\hat{S}^{x}\right]$

In [11]:
print(S2*sx-sx*S2)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


(b) $\left[\hat{S}^{2},\hat{S}^{y}\right]$

In [12]:
print(S2*sy-sy*S2)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


(c) $\left[\hat{S}^{2},\hat{S}^{z}\right]$

In [13]:
print(S2*sz-sz*S2)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


Yes, the result holds that $\hat{S}^{2}$ commutes with each component of spin for general $s$ since $\hat{S}^{2}$ is proportional to the identity matrix (which commutes with any matrix).

4. For spin-$\frac{1}{2}$, verify the square of each component, (e.g., $\left[\hat{S}^{x}\right]^{2}$ is proportional to the identity matrix.)

In [14]:
s = 0.5
sx = spinx(s)
sy = spinx(s)
sz = spinz(s)

print(sx**2)
print(sy**2)
print(sz**2)

[[0.25 0.  ]
 [0.   0.25]]
[[0.25 0.  ]
 [0.   0.25]]
[[0.25 0.  ]
 [0.   0.25]]


This does <b>not</b> hold for $s\neq \frac{1}{2}$. $\hat{S}^{z}$ is at least diagonal, but the others are not. For example:

In [17]:
s = 2.0
sx = spinx(s)
sy = spiny(s)
sz = spinz(s)

print(sx**2)
print(sy**2)
print(sz**2)

[[1.         0.         1.22474487 0.         0.        ]
 [0.         2.5        0.         1.5        0.        ]
 [1.22474487 0.         3.         0.         1.22474487]
 [0.         1.5        0.         2.5        0.        ]
 [0.         0.         1.22474487 0.         1.        ]]
[[ 1.        +0.j  0.        +0.j -1.22474487+0.j  0.        +0.j
   0.        +0.j]
 [ 0.        +0.j  2.5       +0.j  0.        +0.j -1.5       +0.j
   0.        +0.j]
 [-1.22474487+0.j  0.        +0.j  3.        +0.j  0.        +0.j
  -1.22474487+0.j]
 [ 0.        +0.j -1.5       +0.j  0.        +0.j  2.5       +0.j
   0.        +0.j]
 [ 0.        +0.j  0.        +0.j -1.22474487+0.j  0.        +0.j
   1.        +0.j]]
[[4. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 4.]]


Note, however, that we still have $\left[\hat{S}^{x}\right]^{2} + \left[\hat{S}^{x}\right]^{2} + \left[\hat{S}^{x}\right]^{2} = \hbar^{2}s(s+1)\hat{I}$ 

In [18]:
print(sx**2 + sy**2 + sz**2)

[[6.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 6.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 6.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 6.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 6.+0.j]]


### Two spins: entanglement

1. The two-spin basis states follow from taking the tensor products by hand:

$$\left|+\right\rangle \left|+\right\rangle = \left(\begin{array}{c} 1 \\ 0\\ 0 \\ 0\end{array}\right).$$
$$\left|+\right\rangle \left|-\right\rangle = \left(\begin{array}{c} 0 \\ 1\\ 0 \\ 0\end{array}\right).$$
$$\left|-\right\rangle \left|+\right\rangle = \left(\begin{array}{c} 0 \\ 0\\ 1 \\ 0\end{array}\right).$$
$$\left|-\right\rangle \left|-\right\rangle = \left(\begin{array}{c} 0 \\ 0\\ 0 \\ 1\end{array}\right).$$

To verify the Kronecker product, we define the basis states:

In [19]:
plus = array([1.0,0.0])
plus.shape = (2,1)

minus = array([0.0,1.0])
minus.shape = (2,1)

In [20]:
pp = kron(plus,plus)
pm = kron(plus,minus)
mp = kron(minus,plus)
mm = kron(minus,minus)

print(pp)
print(pm)
print(mp)
print(mm)

[[1.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [1.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [1.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [1.]]


Order <b>does</b> matter since kron(plus,minus) and kron(minus,plus) give two <i>different</i> states.

2. Expectation values of $\hat{S}^{z} = \hat{S}^{z}_{1} + \hat{S}^{z}_{2}$:

In [21]:
so = eye(2)
sz = spinz(0.5)

sztot = kron(sz,so) + kron(so,sz)

The expectation values are printed in the order of basis states presented above:

In [22]:
print(asscalar(dot(conj(pp.transpose()),sztot*pp)))
print(asscalar(dot(conj(pm.transpose()),sztot*pm)))
print(asscalar(dot(conj(mp.transpose()),sztot*mp)))
print(asscalar(dot(conj(mm.transpose()),sztot*mm)))

1.0
0.0
0.0
-1.0


3. Exchange operator $\hat{\Pi}$ as a matrix:

(a) Since the middle two states are the only ones mixed up, we have

$$\hat{\Pi} \dot{=} \left(\begin{array}{cccc} 1 & 0 & 0 & 0 \\ 0 & 0 & 1 & 0\\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1\end{array}\right).$$

Numerically,

In [23]:
Pi = matrix(zeros((4,4)))
Pi[0,0] = 1.0
Pi[1,2] = 1.0
Pi[2,1] = 1.0
Pi[3,3] = 1.0

print(Pi)

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


(b) $\hat{\Pi}^{2} = \hat{I}$

In [24]:
print(Pi**2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


(c) Eigenvalues/eigenvectors of $\hat{\Pi}$; note that the eigenvectors are the <i>columns</i> of the output matrix:

In [25]:
eigh(Pi)

(array([-1.,  1.,  1.,  1.]),
 matrix([[ 0.        ,  0.        ,  1.        ,  0.        ],
         [-0.70710678,  0.70710678,  0.        ,  0.        ],
         [ 0.70710678,  0.70710678,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  1.        ]]))

(d) In terms of kets,

$$\left|u_{1}\right\rangle = \frac{1}{\sqrt{2}}\left(\left|-\right\rangle\left|+\right\rangle - \left|+\right\rangle \left|-\right\rangle\right)\;\;\;\;\;\mbox{ for } \lambda = -1,$$
$$\left|u_{2}\right\rangle = \frac{1}{\sqrt{2}}\left(\left|-\right\rangle\left|+\right\rangle + \left|+\right\rangle \left|-\right\rangle\right)\;\;\;\;\;\mbox{ for } \lambda = 1,$$
$$\left|u_{3}\right\rangle = \left|+\right\rangle\left|+\right\rangle \;\;\;\;\;\mbox{ for } \lambda = 1,$$
$$\left|u_{4}\right\rangle = \left|-\right\rangle\left|-\right\rangle \;\;\;\;\;\mbox{ for } \lambda = 1,$$

4. Defining spin operators:

In [26]:
s = 0.5
sx = spinx(s)
sy = spiny(s)
sz = spinz(s)

We combine the operators like $\hat{S}^{z} = \hat{S}^{z}_{1} + \hat{S}^{z}_{2}$

In [27]:
sxt = kron(sx,so) + kron(so,sx)
syt = kron(sy,so) + kron(so,sy)
szt = kron(sz,so) + kron(so,sz)

$\hat{S}^{2}$ follows from squaring the components and adding them:

In [28]:
S2 = (sxt**2) + (syt**2) + (szt**2)
print(S2)

[[2.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 2.+0.j]]


Since the matrix is <i>not</i> diagonal, we can obtain the eigenvectors/eigenvalues numerically:

In [29]:
u,v = eigh(S2)
print(u)
print(v)

[0. 2. 2. 2.]
[[ 0.        +0.j  0.        +0.j  1.        +0.j  0.        +0.j]
 [-0.70710678+0.j  0.70710678+0.j  0.        +0.j  0.        +0.j]
 [ 0.70710678+0.j  0.70710678+0.j  0.        +0.j  0.        +0.j]
 [ 0.        +0.j  0.        +0.j  0.        +0.j  1.        +0.j]]


(a) For an eigenstate of $\hat{S}^{2}$, the eigenvalue corresponds to the value $s(s+1)$ fixing the spin of the system.

(b) There is one eigenvector $\frac{1}{\sqrt{2}}\left(\left|-\right\rangle\left|+\right\rangle - \left|+\right\rangle\left|-\right\rangle\right)$ with eigenvalue $s(s+1) = 0$ corresponding to a spin zero state. 

There are three eigenvectors, $\left|+\right\rangle\left|+\right\rangle$, $\left|-\right\rangle\left|-\right\rangle$, $\frac{1}{\sqrt{2}}\left(\left|-\right\rangle\left|+\right\rangle + \left|+\right\rangle\left|-\right\rangle\right)$, with $s(s+1) = 2$ corresponding to a spin-one "triplet" of states.

The eigenvectors are the <b>same</b> as those for the operator $\hat{\Pi}$.

(c) According to the $\hat{S}^{2}$ operator, the state $\frac{1}{\sqrt{2}}\left(\left|+\right\rangle \left|-\right\rangle - \left|-\right\rangle\left|+\right\rangle\right)$ is a spinless state ($s=0$) while the state $\frac{1}{\sqrt{2}}\left(\left|+\right\rangle\left|-\right\rangle + \left|-\right\rangle\left|+\right\rangle\right)$ is a spin one state <i>with zero projection along the $z$-axis.

5. Expectation values of:

In [30]:
sz = spinz(0.5)
s1z = kron(sz,so)
s2z = kron(so,sz)
s1zs2z = kron(sz,sz)

(a) $\left|+\right\rangle\left|+\right\rangle$

In [31]:
psi = array([1.0,0.0,0.0,0.0])
psi.shape = (4,1)

s1 = asscalar(dot(conj(psi.transpose()),s1z*psi))
s2 = asscalar(dot(conj(psi.transpose()),s2z*psi))
s1s2 = asscalar(dot(conj(psi.transpose()),s1zs2z*psi))

print('<Sz(1)> =',s1)
print('<Sz(2)> =',s2)
print('<Sz(1)Sz(2)> =',s1s2)

<Sz(1)> = 0.5
<Sz(2)> = 0.5
<Sz(1)Sz(2)> = 0.25


(b) $\frac{1}{\sqrt{2}}\left(\left|+\right\rangle \left|-\right\rangle - \left|-\right\rangle \left|+\right\rangle\right)$

In [32]:
psi = array([0.0,1.0/sqrt(2.0),-1.0/sqrt(2.0),0.0])
psi.shape = (4,1)

s1 = asscalar(dot(conj(psi.transpose()),s1z*psi))
s2 = asscalar(dot(conj(psi.transpose()),s2z*psi))
s1s2 = asscalar(dot(conj(psi.transpose()),s1zs2z*psi))

print('<Sz(1)> =',s1)
print('<Sz(2)> =',s2)
print('<Sz(1)Sz(2)> =',s1s2)

<Sz(1)> = 0.0
<Sz(2)> = 0.0
<Sz(1)Sz(2)> = -0.24999999999999994


(c) $\frac{1}{\sqrt{2}}\left(\left|+\right\rangle \left|-\right\rangle + \left|-\right\rangle \left|+\right\rangle\right)$

In [73]:
psi = array([0.0,1.0/sqrt(2.0),1.0/sqrt(2.0),0.0])
psi.shape = (4,1)

s1 = asscalar(dot(conj(psi.transpose()),s1z*psi))
s2 = asscalar(dot(conj(psi.transpose()),s2z*psi))
s1s2 = asscalar(dot(conj(psi.transpose()),s1zs2z*psi))

print('<Sz(1)> =',s1)
print('<Sz(2)> =',s2)
print('<Sz(1)Sz(2)> =',s1s2)

<Sz(1)> = 0.0
<Sz(2)> = 0.0
<Sz(1)Sz(2)> = -0.24999999999999994


(d) $\left|-\right\rangle \left|-\right\rangle$

In [75]:
psi = array([0.0,0.0,0.0,1.0])
psi.shape = (4,1)

s1 = asscalar(dot(conj(psi.transpose()),s1z*psi))
s2 = asscalar(dot(conj(psi.transpose()),s2z*psi))
s1s2 = asscalar(dot(conj(psi.transpose()),s1zs2z*psi))

print('<Sz(1)> =',s1)
print('<Sz(2)> =',s2)
print('<Sz(1)Sz(2)> =',s1s2)

<Sz(1)> = -0.5
<Sz(2)> = -0.5
<Sz(1)Sz(2)> = 0.25


6. Each spin in the superposition states has a vanishing expectation value of spin. However, when the spin is measured it must give $\pm\frac{\hbar}{2}$. Though we can't say with any certainty what value a measurement of the (say) first particle's spin along the $z$ axis will return (both results are equally likely) we <i>can</i> say that the other spin will have the opposite projection of spin. Another way of saying this is that the measurements are <i>highly</i> correlated.